const ADD_CHARACTER = 'ADD_CHARACTER';
const ADD_FAV = 'ADD_FAV';
const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
const REMOVE_FAV = 'REMOVE_FAV';
const FILTER = 'FILTER';
const ORDER = 'ORDER';
const GET_CHARACTER = 'GET_CHARACTER';
const CLEAN_CHARACTERS = 'CLEAN_CHARACTERS';
const CLEAN_CHARACTER = 'CLEAN_CHARACTER';
const SET_LOADING= 'SET_LOADING';
const SHOW_ERROR = 'SHOW_ERROR';
const SET_ERROR = 'SET_ERROR';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT = 'LOGOUT';
module.exports = {
    ADD_CHARACTER,
    ADD_FAV,
    REMOVE_CHARACTER,
	REMOVE_FAV,
    FILTER,
    ORDER,
    GET_CHARACTER,
    CLEAN_CHARACTERS,
    CLEAN_CHARACTER,
    SET_LOADING,
    SHOW_ERROR,
    SET_ERROR,
    LOGIN_SUCCESS,
    LOGOUT
}